/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vocabulario.TESTES.vocabulario;

/**
 *
 * @author francivaldo do nascimento lima
 */
public class vocabulario extends javax.swing.JFrame {

    /**
     * Creates new form vocabulario
     */
    public vocabulario() {
        initComponents();
        jLabelVOCABULARIO.setText("jButton5");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelVOCABULARIO = new javax.swing.JLabel();
        jLabelRESPOSTA = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonPalavra_1 = new javax.swing.JButton();
        jButtonPalavra_2 = new javax.swing.JButton();
        jButtonPalavra_3 = new javax.swing.JButton();
        jButtonPalavra_4 = new javax.swing.JButton();
        jButtonPalavra_5 = new javax.swing.JButton();
        jButtonPalavra_6 = new javax.swing.JButton();
        jButtonPalavra_7 = new javax.swing.JButton();
        jButtonPalavra_8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VOCABULÁRIO");
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 100));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabelVOCABULARIO.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        jLabelVOCABULARIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVOCABULARIO.setText("VOCABULÁRIO");
        jPanel1.add(jLabelVOCABULARIO);

        jLabelRESPOSTA.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelRESPOSTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRESPOSTA.setText("RESPOSTA");
        jPanel1.add(jLabelRESPOSTA);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(153, 255, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jButtonPalavra_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_1.setText("jButton1");
        jButtonPalavra_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_1);

        jButtonPalavra_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_2.setText("jButton2");
        jButtonPalavra_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_2);

        jButtonPalavra_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_3.setText("jButton3");
        jButtonPalavra_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_3);

        jButtonPalavra_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_4.setText("jButton4");
        jButtonPalavra_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_4);

        jButtonPalavra_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_5.setText("jButton5");
        jButtonPalavra_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_5);

        jButtonPalavra_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_6.setText("jButton6");
        jButtonPalavra_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_6);

        jButtonPalavra_7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_7.setText("jButton7");
        jButtonPalavra_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_7);

        jButtonPalavra_8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButtonPalavra_8.setText("jButton8");
        jButtonPalavra_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalavra_8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPalavra_8);

        getContentPane().add(jPanel2);

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("SALVAR");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("CAREGAR VOCABULÁRIO");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPalavra_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_1ActionPerformed
       
        if (jButtonPalavra_1.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_1.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_1.setBackground(new java.awt.Color(255, 51, 51));
        }
        
       // geravocabularios();
        
        
    }//GEN-LAST:event_jButtonPalavra_1ActionPerformed

    private void jButtonPalavra_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_2ActionPerformed
        
        if (jButtonPalavra_2.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_2.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_2.setBackground(new java.awt.Color(255, 51, 51));
        }
        
        
        
    }//GEN-LAST:event_jButtonPalavra_2ActionPerformed

    private void jButtonPalavra_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_3ActionPerformed
        if (jButtonPalavra_3.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_3.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_3.setBackground(new java.awt.Color(255, 51, 51));
        }
    }//GEN-LAST:event_jButtonPalavra_3ActionPerformed

    private void jButtonPalavra_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_4ActionPerformed
        if (jButtonPalavra_4.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_4.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_4.setBackground(new java.awt.Color(255, 51, 51));
        }
    }//GEN-LAST:event_jButtonPalavra_4ActionPerformed

    private void jButtonPalavra_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_5ActionPerformed
         if (jButtonPalavra_5.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_5.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_5.setBackground(new java.awt.Color(255, 51, 51));
        }
    }//GEN-LAST:event_jButtonPalavra_5ActionPerformed

    private void jButtonPalavra_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_6ActionPerformed
        if (jButtonPalavra_6.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_6.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_6.setBackground(new java.awt.Color(255, 51, 51));
        }
    }//GEN-LAST:event_jButtonPalavra_6ActionPerformed

    private void jButtonPalavra_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_7ActionPerformed
         if (jButtonPalavra_7.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_7.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_7.setBackground(new java.awt.Color(255, 51, 51));
        }
    }//GEN-LAST:event_jButtonPalavra_7ActionPerformed

    private void jButtonPalavra_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalavra_8ActionPerformed
        if (jButtonPalavra_8.getText()== jLabelVOCABULARIO.getText())
        {
            jButtonPalavra_8.setBackground(new java.awt.Color(102, 204, 0));
            
        } else{
            
            jButtonPalavra_8.setBackground(new java.awt.Color(255, 51, 51));
        }
    }//GEN-LAST:event_jButtonPalavra_8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    private void geravocabularios() {
        
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vocabulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vocabulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vocabulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vocabulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vocabulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPalavra_1;
    private javax.swing.JButton jButtonPalavra_2;
    private javax.swing.JButton jButtonPalavra_3;
    private javax.swing.JButton jButtonPalavra_4;
    private javax.swing.JButton jButtonPalavra_5;
    private javax.swing.JButton jButtonPalavra_6;
    private javax.swing.JButton jButtonPalavra_7;
    private javax.swing.JButton jButtonPalavra_8;
    private javax.swing.JLabel jLabelRESPOSTA;
    private javax.swing.JLabel jLabelVOCABULARIO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
